export {default as Logo} from './logo.svg';
export {default as DownwardArray} from './downwardarrow.svg';
export {default as Eyeoff} from './eyeoff.svg';
export {default as Eye} from './eye.svg';
export {default as Lock} from './lock.svg';
export {default as Mail} from './mail.svg';
export {default as Person} from './person.svg';
export {default as Plus} from './plus.svg';
export {default as StarEmpty } from './star-empty.svg';
export {default as StarFilled} from './star-filled.svg';
export {default as Search} from './search.svg';
export {default as Add} from './plus.svg';
export {default as Minus} from './minus.svg';
export {default as HomeActive} from './home_active.svg';
export {default as Home} from './home.svg';
export {default as ProfileActive} from './profile_active.svg';
export {default as Profile} from './profile.svg';
export {default as CartActive} from './cart_active.svg';
export {default as Cart} from './cart.svg';
export {default as Delete} from './delete.svg';
export {default as Back} from './back.svg';
export {default as Close} from './close.svg';
export {default as EditIcon} from './editicon.svg'
export {default as Card} from './card.svg'
